development:
  adapter: postgresql
  encoding: utf8
  database: vtv_mailer_development
  username: vtv_mailer
  password: vtv_mailer
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: vtv_mailer_test
  username: vtv_mailer
  password: vtv_mailer
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: vtv_mailer_production
  username: <%= ENV['VTV_MAILER_DATABASE_USER'] %>
  password: <%= ENV['VTV_MAILER_DATABASE_PASSWORD'] %>
  host: localhost
  pool: 5